# Generated by Django 2.0.7 on 2019-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('summary', models.TextField(default='This is cool!')),
            ],
        ),
    ]
